@webapi = http://localhost:5159

GET {{webapi}}/weatherforecast/
Accept: application/json

###
GET {{webapi}}/api/Dishes
Accept: application/json
###
POST {{webapi}}/api/Dishes
Content-Type: application/json

{      
    "Id" : 1,
    "Name"  : "pasta", 
    "Price" : 100, 
    "AvailableBowls" : 20, 
    "ImageUrl" : "", 
    "Category" : "shit "
}
###
POST {{webapi}}/api/Orders/checkout
Content-Type: application/json

{
    "Id": 9,
    "CustomerName" : "joo",
    "Status" : "available",
    "TotalPayment" : 99
}