@webapi = http://localhost:5159
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IkFkbWluVXNlciIsInJvbGUiOiJBZG1pbiIsIm5hbWVpZCI6IjEiLCJuYmYiOjE3Nzc4NDU1MjksImV4cCI6MTc3NzkzMTkyOSwiaWF0IjoxNzc3ODQ1NTI5fQ.x9d_-zNZSEn9cvopA1PqmYsbOMOOyXRb1OvDXPEpns0

### Get all dishes
GET {{webapi}}/api/dishes
Accept: application/json


### Get dish by ID
GET {{webapi}}/api/dishes/1
Accept: application/json


### Filter dishes by category
GET {{webapi}}/api/dishes?categoryId=2


### Add a new dish (requires admin token)
POST {{webapi}}/api/dishes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "chicken ranch Pizza", 
    "Price": 100,
    "CategoryId": 2
}


### Update a dish (requires admin token)
PUT {{webapi}}/api/dishes/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Updated Dish Name", 
    "Price": 150,
    "CategoryId": 1
}


### Checkout an order (requires valid token)
POST {{webapi}}/api/orders/checkout
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "CustomerName" : "joo",
    "Items": 
    [
        {
            "DishId": 1,
            "Quantity": 2
        }

    ]
}


### Get order by ID (requires valid token)
GET {{webapi}}/api/orders/1
Authorization: Bearer {{token}}
Accept: application/json


### Set order status (requires valid token, status can only be 'Pending', 'In Progress', or 'Completed')
PUT {{webapi}}/api/orders/1/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "NewStatus": "Completed"
}


### Delete an order by ID (requires valid token)
DELETE {{webapi}}/api/orders/1
Authorization: Bearer {{token}}


### Get all categories
GET {{webapi}}/api/categories
Accept: application/json


### Get category by ID (requires valid token)
GET {{webapi}}/api/categories/2
Accept: application/json


### Add a new category (requires admin token)
POST {{webapi}}/api/categories/Pizza
Authorization: Bearer {{token}}


### Register a new user (requires admin token)
POST {{webapi}}/api/auth/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Username": "CashierUser",
    "Password": "cashierpassword"
}


### Login to get a token for authentication
POST {{webapi}}/api/auth/login
Content-Type: application/json

{
    "Username": "AdminUser",
    "Password": "adminpassword"
}


### Get user by ID (requires admin token)
GET {{webapi}}/api/users/1
Authorization: Bearer {{token}}
Accept: application/json


### Get all users (requires admin token)
GET {{webapi}}/api/users
Authorization: Bearer {{token}}
Content-Type: application/json


### Delete a user by ID (requires admin token)
### Cannot delete user with ID 1 (admin user), but you can delete other users
DELETE {{webapi}}/api/users/2
Authorization: Bearer {{token}}


### Update a user (requires admin token)
### Cannot update user with ID 1 (admin user), but you can update other users
### You can just include the fields you want to update, but here we will update all fields for demonstration
PUT {{webapi}}/api/users/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Username": "UpdatedUsername",
    "Password": "updatedpassword",
    "Role": "Cashier"
}